export const GET_ALL_HEROES_LIST_SAGA = 'GET_ALL_HEROES_LIST_SAGA';
export const GET_ALL_HEROES_LIST_START = 'GET_ALL_HEROES_LIST_START';
export const GET_ALL_HEROES_LIST_SUCCESS = 'GET_ALL_HEROES_LIST_SUCCESS';
export const GET_ALL_HEROES_LIST_FAIL = 'GET_ALL_HEROES_LIST_FAIL';
