export const GET_ALL_HEROES_LIST_SAGA = 'GET_ALL_HEROES_LIST_SAGA';
export const GET_ALL_HEROES_LIST_START = 'GET_ALL_HEROES_LIST_START';
export const GET_ALL_HEROES_LIST_SUCCESS = 'GET_ALL_HEROES_LIST_SUCCESS';
export const GET_ALL_HEROES_LIST_FAIL = 'GET_ALL_HEROES_LIST_FAIL';

export const FILTER_HEROES_LIST = 'FILTER_HEROES_LIST';

export const GET_HERO_DATA_SAGA = 'GET_HERO_DATA_SAGA';
export const GET_HERO_DATA_START = 'GET_HERO_DATA_START';
export const GET_HERO_DATA_SUCCESS = 'GET_HERO_DATA_SUCCESS';
export const GET_HERO_DATA_FAIL = 'GET_HERO_DATA_FAIL';

export const RESET_HERO_DATA = 'RESET_HERO_DATA';
