export const GET_LATEST_NEWS_SAGA = 'GET_LATEST_NEWS_SAGA';
export const GET_LATEST_NEWS_START = 'GET_LATEST_NEWS_START';
export const GET_LATEST_NEWS_SUCCESS = 'GET_LATEST_NEWS_SUCCESS';
export const GET_LATEST_NEWS_FAIL = 'GET_LATEST_NEWS_FAIL';
