/* eslint-disable max-len */
const heroData = [
  {
    id: 1,
    name: 'npc_dota_hero_antimage',
    npe_desc_loc: '',
    description: '',
    bio: '',
    abilites: [],
  },
  {
    id: 2,
    name: 'npc_dota_hero_axe',
    npe_desc_loc: '',
    description: '',
    bio: '',
    abilites: [],
  },
  {
    id: 3,
    name: 'npc_dota_hero_bane',
    npe_desc_loc: '',
    description: '',
    bio: '',
    abilites: [],
  },
  {
    id: 4,
    name: 'npc_dota_hero_bloodseeker',
    npe_desc_loc: '',
    description: '',
    bio: '',
    abilites: [],
  },
  {
    id: 5,
    name: 'npc_dota_hero_crystal_maiden',
    npe_desc_loc: '',
    description: '',
    bio: '',
    abilites: [],
  },
  {
    id: 6,
    name: 'npc_dota_hero_drow_ranger',
    npe_desc_loc: '',
    description: '',
    bio: '',
    abilites: [],
  },
  {
    id: 7,
    name: 'npc_dota_hero_earthshaker',
    npe_desc_loc: '',
    description: '',
    bio: '',
    abilites: [],
  },
  {
    id: 8,
    name: 'npc_dota_hero_juggernaut',
    npe_desc_loc: '',
    description: '',
    bio: '',
    abilites: [],
  },
  {
    id: 9,
    name: 'npc_dota_hero_mirana',
    npe_desc_loc: '',
    description: '',
    bio: '',
    abilites: [],
  },
  {
    id: 10,
    name: 'npc_dota_hero_morphling',
    npe_desc_loc: '',
    description: '',
    bio: '',
    abilites: [],
  },
  {
    id: 11,
    name: 'npc_dota_hero_nevermore',
    npe_desc_loc: '',
    description: '',
    bio: '',
    abilites: [],
  },
  {
    id: 12,
    name: 'npc_dota_hero_phantom_lancer',
    npe_desc_loc: '',
    description: '',
    bio: '',
    abilites: [],
  },
  {
    id: 13,
    name: 'npc_dota_hero_puck',
    npe_desc_loc: '',
    description: '',
    bio: '',
    abilites: [],
  },
  {
    id: 14,
    name: 'npc_dota_hero_pudge',
    npe_desc_loc: '',
    description: '',
    bio: '',
    abilites: [],
  },
  {
    id: 15,
    name: 'npc_dota_hero_razor',
    npe_desc_loc: '',
    description: '',
    bio: '',
    abilites: [],
  },
  {
    id: 16,
    name: 'npc_dota_hero_sand_king',
    npe_desc_loc: '',
    description: '',
    bio: '',
    abilites: [],
  },
  {
    id: 17,
    name: 'npc_dota_hero_storm_spirit',
    npe_desc_loc: '',
    description: '',
    bio: '',
    abilites: [],
  },
  {
    id: 18,
    name: 'npc_dota_hero_sven',
    npe_desc_loc: '',
    description: '',
    bio: '',
    abilites: [],
  },
  {
    id: 19,
    name: 'npc_dota_hero_tiny',
    npe_desc_loc: '',
    description: '',
    bio: '',
    abilites: [],
  },
  {
    id: 20,
    name: 'npc_dota_hero_vengefulspirit',
    npe_desc_loc: '',
    description: '',
    bio: '',
    abilites: [],
  },
  {
    id: 21,
    name: 'npc_dota_hero_windrunner',
    npe_desc_loc: '',
    description: '',
    bio: '',
    abilites: [],
  },
  {
    id: 22,
    name: 'npc_dota_hero_zuus',
    npe_desc_loc: '',
    description: '',
    bio: '',
    abilites: [],
  },
  {
    id: 23,
    name: 'npc_dota_hero_kunkka',
    npe_desc_loc: '',
    description: '',
    bio: '',
    abilites: [],
  },
  {
    id: 25,
    name: 'npc_dota_hero_lina',
    npe_desc_loc: '',
    description: '',
    bio: '',
    abilites: [],
  },
  {
    id: 26,
    name: 'npc_dota_hero_lion',
    npe_desc_loc: '',
    description: '',
    bio: '',
    abilites: [],
  },
  {
    id: 27,
    name: 'npc_dota_hero_shadow_shaman',
    npe_desc_loc: '',
    description: '',
    bio: '',
    abilites: [],
  },
  {
    id: 28,
    name: 'npc_dota_hero_slardar',
    npe_desc_loc: '',
    description: '',
    bio: '',
    abilites: [],
  },
  {
    id: 29,
    name: 'npc_dota_hero_tidehunter',
    npe_desc_loc: '',
    description: '',
    bio: '',
    abilites: [],
  },
  {
    id: 30,
    name: 'npc_dota_hero_witch_doctor',
    npe_desc_loc: '',
    description: '',
    bio: '',
    abilites: [],
  },
  {
    id: 31,
    name: 'npc_dota_hero_lich',
    npe_desc_loc: '',
    description: '',
    bio: '',
    abilites: [],
  },
  {
    id: 32,
    name: 'npc_dota_hero_riki',
    npe_desc_loc: '',
    description: '',
    bio: '',
    abilites: [],
  },
  {
    id: 33,
    name: 'npc_dota_hero_enigma',
    npe_desc_loc: '',
    description: '',
    bio: '',
    abilites: [],
  },
  {
    id: 34,
    name: 'npc_dota_hero_tinker',
    npe_desc_loc: '',
    description: '',
    bio: '',
    abilites: [],
  },
  {
    id: 35,
    name: 'npc_dota_hero_sniper',
    npe_desc_loc: '',
    description: '',
    bio: '',
    abilites: [],
  },
  {
    id: 36,
    name: 'npc_dota_hero_necrolyte',
    npe_desc_loc: '',
    description: '',
    bio: '',
    abilites: [],
  },
  {
    id: 37,
    name: 'npc_dota_hero_warlock',
    npe_desc_loc: '',
    description: '',
    bio: '',
    abilites: [],
  },
  {
    id: 38,
    name: 'npc_dota_hero_beastmaster',
    npe_desc_loc: '',
    description: '',
    bio: '',
    abilites: [],
  },
  {
    id: 39,
    name: 'npc_dota_hero_queenofpain',
    npe_desc_loc: '',
    description: '',
    bio: '',
    abilites: [],
  },
  {
    id: 40,
    name: 'npc_dota_hero_venomancer',
    npe_desc_loc: '',
    description: '',
    bio: '',
    abilites: [],
  },
  {
    id: 41,
    name: 'npc_dota_hero_faceless_void',
    npe_desc_loc: '',
    description: '',
    bio: '',
    abilites: [],
  },
  {
    id: 42,
    name: 'npc_dota_hero_skeleton_king',
    npe_desc_loc: '',
    description: '',
    bio: '',
    abilites: [],
  },
  {
    id: 43,
    name: 'npc_dota_hero_death_prophet',
    npe_desc_loc: '',
    description: '',
    bio: '',
    abilites: [],
  },
  {
    id: 44,
    name: 'npc_dota_hero_phantom_assassin',
    npe_desc_loc: '',
    description: '',
    bio: '',
    abilites: [],
  },
  {
    id: 45,
    name: 'npc_dota_hero_pugna',
    npe_desc_loc: '',
    description: '',
    bio: '',
    abilites: [],
  },
  {
    id: 46,
    name: 'npc_dota_hero_templar_assassin',
    npe_desc_loc: '',
    description: '',
    bio: '',
    abilites: [],
  },
  {
    id: 47,
    name: 'npc_dota_hero_viper',
    npe_desc_loc: '',
    description: '',
    bio: '',
    abilites: [],
  },
  {
    id: 48,
    name: 'npc_dota_hero_luna',
    npe_desc_loc: '',
    description: '',
    bio: '',
    abilites: [],
  },
  {
    id: 49,
    name: 'npc_dota_hero_dragon_knight',
    npe_desc_loc: '',
    description: '',
    bio: '',
    abilites: [],
  },
  {
    id: 50,
    name: 'npc_dota_hero_dazzle',
    npe_desc_loc: '',
    description: '',
    bio: '',
    abilites: [],
  },
  {
    id: 51,
    name: 'npc_dota_hero_rattletrap',
    npe_desc_loc: '',
    description: '',
    bio: '',
    abilites: [],
  },
  {
    id: 52,
    name: 'npc_dota_hero_leshrac',
    npe_desc_loc: '',
    description: '',
    bio: '',
    abilites: [],
  },
  {
    id: 53,
    name: 'npc_dota_hero_furion',
    npe_desc_loc: '',
    description: '',
    bio: '',
    abilites: [],
  },
  {
    id: 54,
    name: 'npc_dota_hero_life_stealer',
    npe_desc_loc: '',
    description: '',
    bio: '',
    abilites: [],
  },
  {
    id: 55,
    name: 'npc_dota_hero_dark_seer',
    npe_desc_loc: '',
    description: '',
    bio: '',
    abilites: [],
  },
  {
    id: 56,
    name: 'npc_dota_hero_clinkz',
    npe_desc_loc: '',
    description: '',
    bio: '',
    abilites: [],
  },
  {
    id: 57,
    name: 'npc_dota_hero_omniknight',
    npe_desc_loc: '',
    description: '',
    bio: '',
    abilites: [],
  },
  {
    id: 58,
    name: 'npc_dota_hero_enchantress',
    npe_desc_loc: '',
    description: '',
    bio: '',
    abilites: [],
  },
  {
    id: 59,
    name: 'npc_dota_hero_huskar',
    npe_desc_loc: '',
    description: '',
    bio: '',
    abilites: [],
  },
  {
    id: 60,
    name: 'npc_dota_hero_night_stalker',
    npe_desc_loc: '',
    description: '',
    bio: '',
    abilites: [],
  },
  {
    id: 61,
    name: 'npc_dota_hero_broodmother',
    npe_desc_loc: '',
    description: '',
    bio: '',
    abilites: [],
  },
  {
    id: 62,
    name: 'npc_dota_hero_bounty_hunter',
    npe_desc_loc: '',
    description: '',
    bio: '',
    abilites: [],
  },
  {
    id: 63,
    name: 'npc_dota_hero_weaver',
    npe_desc_loc: '',
    description: '',
    bio: '',
    abilites: [],
  },
  {
    id: 64,
    name: 'npc_dota_hero_jakiro',
    npe_desc_loc: '',
    description: '',
    bio: '',
    abilites: [],
  },
  {
    id: 65,
    name: 'npc_dota_hero_batrider',
    npe_desc_loc: '',
    description: '',
    bio: '',
    abilites: [],
  },
  {
    id: 66,
    name: 'npc_dota_hero_chen',
    npe_desc_loc: '',
    description: '',
    bio: '',
    abilites: [],
  },
  {
    id: 67,
    name: 'npc_dota_hero_spectre',
    npe_desc_loc: '',
    description: '',
    bio: '',
    abilites: [],
  },
  {
    id: 68,
    name: 'npc_dota_hero_ancient_apparition',
    npe_desc_loc: 'Launches a powerful icy blast from anywhere on the map',
    description:
      "Able to launch a powerful blast of <b>damaging ice</b> across the battlefield, Ancient Apparition threatens to shatter weakened enemies wherever they are. Slowing enemies as he enhances his allies' effectiveness in battle, he is a constant threat to his foes.",
    bio: "Kaldr, the Ancient Apparition, is an image projected from outside time. He springs from the cold, infinite void that both predates the universe and awaits its end. Kaldr is, Kaldr was, Kaldr shall be...and what we perceive, powerful as it appears to us, is but the faintest faded echo of the true, eternal Kaldr. Some believe that as the cosmos ages and approaches its final moments, the brightness and power of Kaldr will also intensify--that the Ancient Apparition will grow younger and stronger as eternity's end draws nigh. His grip of ice will bring all matter to a stop, his image will cast a light too terrible to behold. An Apparition no longer!",
    abilites: [
      {
        locilized_name: 'ancient_apparition_cold_feet',
        isAgs: false,
        isAgsShard: false,
        cooldown: '12.0 / 11.0 / 10.0 / 9.0',
        mana_cost: '125',
        name: 'COLD FEET',
        description:
          "Places a frozen hex on an enemy unit that deals damage over time, but can be dispelled by moving away from the initial cast point.  If the enemy unit doesn't move outside of the given range, it will be stunned and frozen in place after 4 seconds.",
        trivia_description:
          "Kaldr's presence draws those around him into a frozen void, threatening to lock them in an icy prison for eternity.",
        ability_info: [
          {
            name: 'ABILITY',
            value: 'Unit Target',
          },
          {
            name: 'PIERCES SPELL IMMUNITY',
            value: 'No',
          },
          {
            name: 'AFFECTS',
            value: 'Enemy Units',
          },
          {
            name: 'DISPELLABLE',
            value: 'Yes',
          },
          {
            name: 'DAMAGE TYPE',
            value: 'Magical',
          },
        ],
        ability_stats: [
          {
            value: '30.0 / 50.0 / 70.0 / 90.0',
            name: 'DAMAGE PER TICK',
          },
          {
            value: '715',
            name: 'BREAK DISTANCE',
          },
          {
            value: '2.0 / 2.5 / 3.0 / 3.5',
            name: 'STUN DURATION',
          },
          {
            value: '700 / 800 / 900 / 1000',
            name: 'CAST RANGE',
          },
        ],
      },
      {
        locilized_name: 'ancient_apparition_ice_vortex',
        isAgs: false,
        isAgsShard: false,
        cooldown: '7.0 / 6.0 / 5.0 / 4.0',
        mana_cost: '40 / 50 / 60 / 70',
        name: 'ICE VORTEX',
        description:
          'Creates a vortex of icy energy that slows and increases magic damage done to enemies in its range.',
        trivia_description:
          'Frozen, caustic winds are at the whim of Kaldr, chilling the field of battle.',
        ability_info: [
          {
            name: 'ABILITY',
            value: 'Point Target',
          },
          {
            name: 'PIERCES SPELL IMMUNITY',
            value: 'No',
          },
          {
            name: 'DISPELLABLE',
            value: 'No',
          },
        ],
        ability_stats: [
          {
            name: 'RADIUS',
            value: '275',
          },
          {
            name: 'SLOW',
            value: '15% / -20% / -25% / -30%',
          },
          {
            name: 'INCREASED MAGIC DAMAGE',
            value: '-12% / -16% / -20% / -24%',
          },
          {
            name: 'DURATION',
            value: '16',
          },
        ],
      },
      {
        locilized_name: 'ancient_apparition_chilling_touch',
        isAgs: false,
        isAgsShard: false,
        cooldown: '15.0 / 11.0 / 7.0 / 3.0',
        mana_cost: '30 / 45 / 60 / 75',
        name: 'CHILLING TOUCH',
        description:
          "Enhances Ancient Apparition's attack with increased range, heavy magic damage, and movement slow..",
        trivia_description:
          "The Ancient Apparition's eternal knowledge brings a frigid enchantment to his attacks.",
        ability_info: [
          {
            name: 'ABILITY',
            value: 'Enemy Unit',
          },
          {
            name: 'PIERCES SPELL IMMUNITY',
            value: 'No',
          },
          {
            name: 'AFFECTS',
            value: 'Enemy Unit',
          },
          {
            name: 'DISPELLABLE',
            value: 'Yes',
          },
        ],
        ability_stats: [
          {
            name: 'DAMAGE',
            value: '50 / 90 / 130 / 170',
          },
          {
            name: 'MOVEMENT SLOW',
            value: '100%',
          },
          {
            name: 'SLOW DURATION',
            value: '0.5',
          },
          {
            name: 'ATTACK RANGE BONUS',
            value: '60 / 120 / 180 / 240',
          },
        ],
      },
      {
        locilized_name: 'ancient_apparition_ice_blast',
        isAgs: false,
        isAgsShard: false,
        cooldown: '60.0 / 50.0 / 40.0',
        mana_cost: '175',
        name: 'ICE BLAST',
        description:
          "Launches a tracer toward any location on the battlefield, which must be triggered again to mark the area to be blasted by a damaging explosion of hail. The further the tracer travels, the larger the explosion will be. Enemies caught in the explosion, or who touch the icy ball of hail as it travels, are Frostbitten, taking damage and prevented from regenerating or healing. If a Frostbitten unit's health drops below a certain percentage, they will instantly shatter.",
        trivia_description:
          "Ice storms from ages past flow through Kaldr's frosty limbs, crashing into the world and turning its inhabitants into monuments to his eternal power.",
        ability_info: [
          {
            name: 'ABILITY',
            value: 'Point Target',
          },
          {
            name: 'DISPELLABLE',
            value: 'Yes',
          },
          {
            name: 'DAMAGE TYPE',
            value: 'Magical',
          },
          {
            name: 'DISPELLABLE',
            value: 'No',
          },
        ],
        ability_stats: [
          {
            name: 'DAMAGE',
            value: '250 / 325 / 400',
          },
          {
            name: 'FROSTBITTEN DURATION',
            value: '10.0 / 11.0 / 12.0',
          },
          {
            name: 'FROSTBITTEN DAMAGE PER SECOND',
            value: '12.5 / 20.0 / 32.0',
          },
          {
            name: 'SHATTER HEALTH THRESHOLD',
            value: '12.0% / 13.0% / 14.0%',
          },
        ],
      },
      {
        locilized_name: 'ancient_apparition_aghanims_shard',
        isAgs: false,
        isAgsShard: true,
        imgUrl: 'ancient_apparition_ice_vortex',
        cooldown: null,
        mana_cost: null,
        name: 'ICE VORTEX',
        description: 'Causes Ice Vortex to deal 40 DPS and reduces attack speed by 20.',
        trivia_description: null,
        ability_info: null,
        ability_stats: null,
      },
      {
        locilized_name: 'ancient_apparition_aghanims_scepter',
        isAgs: true,
        isAgsShard: false,
        imgUrl: 'ancient_apparition_chilling_touch',
        cooldown: '15.0 / 11.0 / 7.0 / 3.0',
        mana_cost: '30 / 45 / 60 / 75',
        name: 'CHILLING TOUCH',
        description: 'Removes cooldown and reduces manacost by half.',
        trivia_description:
          "The Ancient Apparition's eternal knowledge brings a frigid enchantment to his attacks.",
        ability_info: null,
        ability_stats: null,
      },
    ],
  },
  {
    id: 69,
    name: 'npc_dota_hero_doom_bringer',
    npe_desc_loc: '',
    description: '',
    bio: '',
    abilites: [],
  },
  {
    id: 70,
    name: 'npc_dota_hero_ursa',
    npe_desc_loc: '',
    description: '',
    bio: '',
    abilites: [],
  },
  {
    id: 71,
    name: 'npc_dota_hero_spirit_breaker',
    npe_desc_loc: '',
    description: '',
    bio: '',
    abilites: [],
  },
  {
    id: 72,
    name: 'npc_dota_hero_gyrocopter',
    npe_desc_loc: '',
    description: '',
    bio: '',
    abilites: [],
  },
  {
    id: 73,
    name: 'npc_dota_hero_alchemist',
    npe_desc_loc: 'Earns extra gold from unit kills and bounty runes',
    description:
      'Synthesizing <b>extra resources</b> from each and every kill, Alchemist has no trouble gathering the tools needed to destroy his foes. Ambushing enemies with <b>corrosive acid</b> and a host of <b>unstable chemicals</b>, he battles to ensure his greedy escapades can remain uninterrupted.',
    bio: "The sacred science of Chymistry was a Darkbrew family tradition, but no Darkbrew had ever shown the kind of creativity, ambition, and recklessness of young Razzil. However, when adulthood came calling he pushed aside the family trade to try his hand at manufacturing gold through Alchemy.\r\n\t\t\t\t<br><br>In an act of audacity befitting his reputation, Razzil announced he would transmute an entire mountain into gold. Following two decades of research and spending and preparation, he failed spectacularly, quickly finding himself imprisoned for the widespread destruction his experiment wrought. Yet Razzil was never one to take a setback lightly, and sought escape to continue his research.\r\n\t\t\t\t<br><br>When his new cellmate turned out to be a fierce ogre, he found just the opportunity he needed. After convincing the ogre not to eat him, Razzil set about carefully concocting a tincture for it to drink, made from the moulds and mosses growing in the prison stone work. In a week's time, it seemed ready. When the ogre drank the potion, it flew into an unstoppable berserker rage, destroying the cell bars and exploding through walls and guards alike.\r\n\t\t\t\t<br><br>They soon found themselves lost somewhere in the forest surrounding the city with a trail of wreckage in their wake and no signs of pursuit.  In the tonic's afterglow, the ogre seemed serene, happy, and even eager. Resolving to work together, the pair set off to collect the materials needed to attempt Razzil's Alchemic transmutation once more.",
    abilites: [
      {
        locilized_name: 'alchemist_acid_spray',
        isAgs: false,
        isAgsShard: false,
        cooldown: '22.0',
        mana_cost: '130 / 140 / 150 / 160',
        name: 'ACID SPRAY',
        description:
          'Sprays high-pressure acid across a target area. Enemy units who step across the contaminated terrain take damage per second and have their armor reduced.',
        trivia_description:
          'Using traditional Alchemy from the Darkbrew family, Razzil concocts an acid that dissolves even the toughest metals.',
        ability_info: [
          {
            name: 'ABILITY',
            value: 'Point Target',
          },
          {
            name: 'PIERCES SPELL IMMUNITY',
            value: 'No',
          },
          {
            name: 'DAMAGE TYPE',
            value: 'Physical',
          },
        ],
        ability_stats: [
          {
            name: 'RADIUS',
            value: '475 / 525 / 575 / 625',
          },
          {
            name: 'DURATION',
            value: '16.0',
          },
          {
            name: 'DAMAGE PER SECOND',
            value: '0 / 25 / 30 / 35',
          },
          {
            name: 'ARMOR REDUCTION',
            value: '4 / 5 / 6 / 7',
          },
        ],
      },
      {
        locilized_name: 'alchemist_unstable_concoction',
        isAgs: false,
        isAgsShard: false,
        cooldown: '5.5',
        mana_cost: '50',
        name: 'UNSTABLE CONCOCTION',
        description:
          'Alchemist brews up an unstable concoction that he can throw at an enemy hero, to stun and deal damage in an area around the explosion. The longer the concoction brews, the more damage it deals and the longer the stun. After 5.0 seconds, the brew reaches its maximum damage and stun time. However, after 5.5 seconds, the concoction will explode on Alchemist himself if not thrown.',
        trivia_description:
          'A silver lining to the failure of turning a mountain into gold, this volatile solution has destructive potential.',
        ability_info: [
          {
            name: 'ABILITY',
            value: 'No Target',
          },
          {
            name: 'PIERCES SPELL IMMUNITY',
            value: 'No',
          },
          {
            name: 'DAMAGE TYPE',
            value: 'Magical',
          },
          {
            name: 'DISPELLABLE',
            value: 'Only Strong Dispels',
          },
        ],
        ability_stats: [
          {
            name: 'MAX STUN',
            value: '1.8 / 2.5 / 3.3 / 4.0',
          },
          {
            name: 'MAX DAMAGE',
            value: '150 / 220 / 290 / 360',
          },
          {
            name: 'EXPLOSION RADIUS',
            value: '250',
          },
        ],
      },
      {
        locilized_name: 'alchemist_goblins_greed',
        isAgs: false,
        isAgsShard: false,
        cooldown: null,
        mana_cost: null,
        name: "GREEVIL'S GREED",
        description:
          'Alchemist synthesizes additional gold from his enemies and bounty runes. With each kill, Alchemist earns base bonus gold and extra bonus gold. If Alchemist kills another unit which yields gold within the next 36 seconds, an additional instance of Extra Bonus Gold is added to the total. Additionally, causes bounty runes to yield more gold.',
        trivia_description:
          'While it is not a mountain, Razzil has mastered the conversion of smaller compounds to line his pockets.',
        ability_info: [
          {
            name: 'ABILITY',
            value: 'Passive',
          },
          {
            name: 'AFFECTS',
            value: 'Allied Heroes',
          },
        ],
        ability_stats: [
          {
            name: 'RECENT KILL WINDOW',
            value: '36',
          },
          {
            name: 'BASE BONUS GOLD',
            value: '3',
          },
          {
            name: 'EXTRA BONUS GOLD',
            value: '3',
          },
          {
            name: 'MAX BONUS GOLD PER KILL',
            value: '15 / 18 / 21 / 24',
          },
          {
            name: 'BOUNTY RUNE MULTIPLIER:',
            value: '1.5 / 2.0 / 2.5 / 3.0',
          },
        ],
      },
      {
        locilized_name: 'alchemist_chemical_rage',
        isAgs: false,
        isAgsShard: false,
        cooldown: '55.0',
        mana_cost: '50 / 75 / 100',
        name: 'CHEMICAL RAGE',
        description:
          'Alchemist causes his Ogre to enter a chemically induced rage, reducing base attack cooldown and increasing movement speed and health regeneration.<br />DISPEL TYPE: Basic Dispel',
        trivia_description:
          'The brew Razzil gave to the Ogre during their prison bust has become a useful potion in the midst of combat.',
        ability_info: [
          {
            name: 'ABILITY',
            value: 'No Target',
          },
          {
            name: 'DISPELLABLE',
            value: 'No',
          },
        ],
        ability_stats: [
          {
            name: 'DURATION',
            value: '25.0',
          },
          {
            name: 'BASE ATTACK TIME',
            value: '1.2 / 1.1 / 1.0',
          },
          {
            name: 'BONUS HEALTH REGEN',
            value: '50 / 75 / 100',
          },
          {
            name: 'BONUS MOVE SPEED',
            value: '40 / 50 / 60',
          },
          {
            name: 'SCEPTER BONUS DAMAG',
            value: '20',
          },
          {
            name: 'SCEPTER SPELL AMP',
            value: '5%',
          },
        ],
      },
      {
        locilized_name: 'alchemist_aghanims_shard',
        isAgs: false,
        isAgsShard: true,
        imgUrl: 'alchemist_berserk_potion',
        cooldown: '35.0',
        mana_cost: '125',
        name: 'CURSE OF AVERNUS',
        description:
          'Alchemist throws a potion at an ally, applying a basic dispel and giving them 50 Attack Speed, 30 Movement Speed and 40 HP regen.<br />Lasts 10.0 seconds.',
        trivia_description: null,
        ability_info: [
          {
            name: 'ABILITY',
            value: 'Unit Target',
          },
          {
            name: 'PIERCES SPELL IMMUNITY',
            value: 'Yes',
          },
          {
            name: 'DAMAGE TYPE',
            value: 'Magical',
          },
          {
            name: 'DISPELLABLE',
            value: 'Yes',
          },
        ],
        ability_stats: [
          {
            name: 'DURATION',
            value: '10.0',
          },
          {
            name: 'ATTACK SPEED',
            value: '50',
          },
          {
            name: 'HEALTH REGEN',
            value: '40',
          },
        ],
      },
      {
        locilized_name: 'alchemist_aghanims_scepter',
        isAgs: true,
        isAgsShard: false,
        imgUrl: 'alchemist_chemical_rage',
        cooldown: '55.0',
        mana_cost: '50 / 75 / 100',
        name: 'BORROWED TIME',
        description:
          "Alchemist melts down Aghanim's Scepter to grant an allied hero all Aghanim's Scepter upgrades. When you have a Scepter of your own, you will gain bonus damage and spell amplification for each gifted Scepter.",
        trivia_description:
          'The brew Razzil gave to the Ogre during their prison bust has become a useful potion in the midst of combat.',
        ability_info: null,
        ability_stats: null,
      },
    ],
  },
  {
    id: 74,
    name: 'npc_dota_hero_invoker',
    npe_desc_loc: '',
    description: '',
    bio: '',
    abilites: [],
  },
  {
    id: 75,
    name: 'npc_dota_hero_silencer',
    npe_desc_loc: '',
    description: '',
    bio: '',
    abilites: [],
  },
  {
    id: 76,
    name: 'npc_dota_hero_obsidian_destroyer',
    npe_desc_loc: '',
    description: '',
    bio: '',
    abilites: [],
  },
  {
    id: 77,
    name: 'npc_dota_hero_lycan',
    npe_desc_loc: '',
    description: '',
    bio: '',
    abilites: [],
  },
  {
    id: 78,
    name: 'npc_dota_hero_brewmaster',
    npe_desc_loc: '',
    description: '',
    bio: '',
    abilites: [],
  },
  {
    id: 79,
    name: 'npc_dota_hero_shadow_demon',
    npe_desc_loc: '',
    description: '',
    bio: '',
    abilites: [],
  },
  {
    id: 80,
    name: 'npc_dota_hero_lone_druid',
    npe_desc_loc: '',
    description: '',
    bio: '',
    abilites: [],
  },
  {
    id: 81,
    name: 'npc_dota_hero_chaos_knight',
    npe_desc_loc: '',
    description: '',
    bio: '',
    abilites: [],
  },
  {
    id: 82,
    name: 'npc_dota_hero_meepo',
    npe_desc_loc: '',
    description: '',
    bio: '',
    abilites: [],
  },
  {
    id: 83,
    name: 'npc_dota_hero_treant',
    npe_desc_loc: '',
    description: '',
    bio: '',
    abilites: [],
  },
  {
    id: 84,
    name: 'npc_dota_hero_ogre_magi',
    npe_desc_loc: '',
    description: '',
    bio: '',
    abilites: [],
  },
  {
    id: 85,
    name: 'npc_dota_hero_undying',
    npe_desc_loc: '',
    description: '',
    bio: '',
    abilites: [],
  },
  {
    id: 86,
    name: 'npc_dota_hero_rubick',
    npe_desc_loc: '',
    description: '',
    bio: '',
    abilites: [],
  },
  {
    id: 87,
    name: 'npc_dota_hero_disruptor',
    npe_desc_loc: '',
    description: '',
    bio: '',
    abilites: [],
  },
  {
    id: 88,
    name: 'npc_dota_hero_nyx_assassin',
    npe_desc_loc: '',
    description: '',
    bio: '',
    abilites: [],
  },
  {
    id: 89,
    name: 'npc_dota_hero_naga_siren',
    npe_desc_loc: '',
    description: '',
    bio: '',
    abilites: [],
  },
  {
    id: 90,
    name: 'npc_dota_hero_keeper_of_the_light',
    npe_desc_loc: '',
    description: '',
    bio: '',
    abilites: [],
  },
  {
    id: 91,
    name: 'npc_dota_hero_wisp',
    npe_desc_loc: '',
    description: '',
    bio: '',
    abilites: [],
  },
  {
    id: 92,
    name: 'npc_dota_hero_visage',
    npe_desc_loc: '',
    description: '',
    bio: '',
    abilites: [],
  },
  {
    id: 93,
    name: 'npc_dota_hero_slark',
    npe_desc_loc: '',
    description: '',
    bio: '',
    abilites: [],
  },
  {
    id: 94,
    name: 'npc_dota_hero_medusa',
    npe_desc_loc: '',
    description: '',
    bio: '',
    abilites: [],
  },
  {
    id: 95,
    name: 'npc_dota_hero_troll_warlord',
    npe_desc_loc: '',
    description: '',
    bio: '',
    abilites: [],
  },
  {
    id: 96,
    name: 'npc_dota_hero_centaur',
    npe_desc_loc: '',
    description: '',
    bio: '',
    abilites: [],
  },
  {
    id: 97,
    name: 'npc_dota_hero_magnataur',
    npe_desc_loc: '',
    description: '',
    bio: '',
    abilites: [],
  },
  {
    id: 98,
    name: 'npc_dota_hero_shredder',
    npe_desc_loc: '',
    description: '',
    bio: '',
    abilites: [],
  },
  {
    id: 99,
    name: 'npc_dota_hero_bristleback',
    npe_desc_loc: '',
    description: '',
    bio: '',
    abilites: [],
  },
  {
    id: 100,
    name: 'npc_dota_hero_tusk',
    npe_desc_loc: '',
    description: '',
    bio: '',
    abilites: [],
  },
  {
    id: 101,
    name: 'npc_dota_hero_skywrath_mage',
    npe_desc_loc: '',
    description: '',
    bio: '',
    abilites: [],
  },
  {
    id: 102,
    name: 'npc_dota_hero_abaddon',
    npe_desc_loc: 'Shields his allies or himself from attacks',
    description:
      'Able to transform enemy attacks into <b>self-healing</b>, Abaddon can survive almost any assault. <b>Shielding allies</b> and launching his <b>double-edged coil</b> at a friend or foe, he is always ready to ride into the thick of battle.',
    bio: "The Font of Avernus is the source of a family's strength, a crack in primal stones from which vapors of prophetic power have issued for generations. Each newborn of the cavernous House Avernus is bathed in the black mist, and by this baptism they are given an innate connection to the mystic energies of the land. They grow up believing themselves fierce protectors of their lineal traditions, the customs of the realm--but what they really are protecting is the Font itself. And the motives of the mist are unclear.\r\n\t\t\t\t<br><br>When the infant Abaddon was bathed in the Font, they say something went awry. In the child's eyes there flared a light of comprehension that startled all present and set the sacerdotes to whispering. He was raised with every expectation of following the path all scions of Avernus took--to train in war, that in times of need he might lead the family's army in defense of the ancestral lands. But Abaddon was always one apart. Where others trained with weapons, he bent himself to meditation in the presence of the mist. He drank deep from the vapors that welled from the Font, learning to blend his spirit with the potency that flowed from far beneath the House; he became a creature of the black mist.\r\n\t\t\t\t<br><br>There was bitterness within the House Avernus--elders and young alike accusing him of neglecting his responsibilities. But all such accusations stopped when Abaddon rode into battle, and they saw how the powers of the mist had given him mastery over life and death beyond those of any lord the House had ever known.",
    role_levels: [1, 2, 0, 0, 0, 2, 0, 0, 0],
    turn_rate: 0.6000000238418579,
    sight_range_day: 1800,
    sight_range_night: 800,
    abilites: [
      {
        locilized_name: 'abaddon_death_coil',
        isAgs: false,
        isAgsShard: false,
        cooldown: '5.5',
        mana_cost: '50',
        name: 'MIST COIL',
        description:
          "Abaddon releases a coil of deathly mist that can damage an enemy unit or heal a friendly unit at the cost of some of Abaddon's health",
        trivia_description:
          'A mysterious vapor from the Font of Avernus now infuses the breath of Abaddon, who releases it at will.',
        ability_info: [
          {
            name: 'ABILITY',
            value: 'Unit Target',
          },
          {
            name: 'PIERCES SPELL IMMUNITY',
            value: 'Allies Yes Enemies No',
          },
          {
            name: 'AFFECTS',
            value: 'Heroes',
          },
          {
            name: 'DAMAGE TYPE',
            value: 'Magical',
          },
        ],
        ability_stats: [
          {
            name: 'SELF DAMAGE',
            value: '50.0%',
          },
          {
            name: 'DAMAGE/HEAL',
            value: '110.0 / 160.0 / 210.0 / 260.0',
          },
          {
            name: 'CAST RANGE',
            value: '575',
          },
        ],
      },
      {
        locilized_name: 'abaddon_aphotic_shield',
        isAgs: false,
        isAgsShard: false,
        cooldown: '5.5',
        mana_cost: '50',
        name: 'APHOTIC SHIELD',
        description:
          'Summons dark energies around an ally unit, creating a shield that absorbs a set amount of damage before expiring. When the shield is destroyed it will burst and deal damage equal to the amount it could absorb to an area around it. Removes certain types of negative buffs and stuns on cast.<br />DISPEL TYPE: Strong Dispel',
        trivia_description:
          'The powers of the black mist rise to absorb attacks like the black mist absorbs light.',
        ability_info: [
          {
            name: 'ABILITY',
            value: 'Unit Target',
          },
          {
            name: 'PIERCES SPELL IMMUNITY',
            value: 'No',
          },
          {
            name: 'AFFECTS',
            value: 'Allied Units',
          },
          {
            name: 'DAMAGE TYPE',
            value: 'Magical',
          },
        ],
        ability_stats: [
          {
            name: 'DURATION',
            value: '15.0',
          },
          {
            name: 'MAX DAMAGE ABSORBED',
            value: '110.0 / 140.0 / 170.0 / 200.0',
          },
          {
            name: 'BURST RADIUS',
            value: '675',
          },
        ],
      },
      {
        locilized_name: 'abaddon_frostmourne',
        isAgs: false,
        isAgsShard: false,
        cooldown: null,
        mana_cost: null,
        name: 'CURSE OF AVERNUS',
        description:
          "Abaddon strikes an enemy, slowing the target's movement speed. If the target gets hit 4 times, they become affected by a chilling curse causing them to be silenced and slowed, and all attacks against them gain an attack speed boost.",
        trivia_description:
          'While the baptized draw strength from the Font, the gifts of Avernus are debilitating to the uninitiated.',
        ability_info: [
          {
            name: 'ABILITY',
            value: 'Passive',
          },
          {
            name: 'PIERCES SPELL IMMUNITY',
            value: 'No',
          },
          {
            name: 'DISPELLABLE',
            value: 'Yes',
          },
        ],
        ability_stats: [
          {
            name: 'BASIC DURATION',
            value: '5.0',
          },
          {
            name: 'BASIC SLOW',
            value: '10% / 15% / 20% / 25%',
          },
          {
            name: 'CURSE DURATION',
            value: '4.5',
          },
          {
            name: 'CURSE SLOW',
            value: '15% / 30% / 45% / 60%',
          },
          {
            name: 'CURSE ATTACK SPEED',
            value: '40 / 60 / 80 / 100',
          },
        ],
      },
      {
        locilized_name: 'abaddon_borrowed_time',
        isAgs: false,
        isAgsShard: false,
        cooldown: '60.0 / 50.0 / 40.0',
        mana_cost: '0 / 0 / 0',
        name: 'BORROWED TIME',
        description:
          'When activated, all damage dealt to you will heal instead of harm. Most negative buffs will also be removed. If the ability is not on cooldown, it will automatically activate if your health falls below 400.<br />DISPEL TYPE: Strong Dispel',
        trivia_description:
          'The most unnatural of all the gifts of the Font of Avernus, this power defies mortal understanding. What should hurt, instead heals; and what should kill gives strength anew.',
        ability_info: [
          {
            name: 'ABILITY',
            value: 'No Target',
          },
          {
            name: 'DISPELLABLE',
            value: 'No',
          },
        ],
        ability_stats: [
          {
            name: 'HEALTH THRESHOLD',
            value: '400',
          },
          {
            name: 'DURATION',
            value: '4.0 / 5.0 / 6.0',
          },
          {
            name: 'SCEPTER DURATION',
            value: '7.0 / 8.0 / 9.0',
          },
          {
            name: 'SCEPTER DAMAGE THRESHOLD',
            value: '525',
          },
          {
            name: 'SCEPTER RANGE',
            value: '1600',
          },
        ],
      },
      {
        locilized_name: 'abaddon_aghanims_shard',
        isAgs: false,
        isAgsShard: true,
        imgUrl: 'abaddon_frostmourne',
        cooldown: '60.0 / 50.0 / 40.0',
        mana_cost: '0 / 0 / 0',
        name: 'CURSE OF AVERNUS',
        description:
          'Causes Mist Coil and Aphotic Shield to apply a Curse of Avernus stack on enemies. Increase base slow by 10%. Lowers Cooldown for Mist Coil and Aphotic Shield by 1 second.',
        trivia_description: null,
        ability_info: null,
        ability_stats: null,
      },
      {
        locilized_name: 'abaddon_aghanims_scepter',
        isAgs: true,
        isAgsShard: false,
        imgUrl: 'abaddon_borrowed_time',
        cooldown: '60.0 / 50.0 / 40.0',
        mana_cost: '0 / 0 / 0',
        name: 'BORROWED TIME',
        description:
          'Increases duration. While Borrowed Time is active, anytime an ally takes more than 525 damage while within 1600 range of Abaddon, an individual Mist Coil will automatically fire towards that ally.',
        trivia_description:
          'The most unnatural of all the gifts of the Font of Avernus, this power defies mortal understanding. What should hurt, instead heals; and what should kill gives strength anew.',
        ability_info: null,
        ability_stats: null,
      },
    ],
  },
  {
    id: 103,
    name: 'npc_dota_hero_elder_titan',
    npe_desc_loc: '',
    description: '',
    bio: '',
    abilites: [],
  },
  {
    id: 104,
    name: 'npc_dota_hero_legion_commander',
    npe_desc_loc: '',
    description: '',
    bio: '',
    abilites: [],
  },
  {
    id: 105,
    name: 'npc_dota_hero_techies',
    npe_desc_loc: '',
    description: '',
    bio: '',
    abilites: [],
  },
  {
    id: 106,
    name: 'npc_dota_hero_ember_spirit',
    npe_desc_loc: '',
    description: '',
    bio: '',
    abilites: [],
  },
  {
    id: 107,
    name: 'npc_dota_hero_earth_spirit',
    npe_desc_loc: '',
    description: '',
    bio: '',
    abilites: [],
  },
  {
    id: 108,
    name: 'npc_dota_hero_abyssal_underlord',
    npe_desc_loc: '',
    description: '',
    bio: '',
    abilites: [],
  },
  {
    id: 109,
    name: 'npc_dota_hero_terrorblade',
    npe_desc_loc: '',
    description: '',
    bio: '',
    abilites: [],
  },
  {
    id: 110,
    name: 'npc_dota_hero_phoenix',
    npe_desc_loc: '',
    description: '',
    bio: '',
    abilites: [],
  },
  {
    id: 111,
    name: 'npc_dota_hero_oracle',
    npe_desc_loc: '',
    description: '',
    bio: '',
    abilites: [],
  },
  {
    id: 112,
    name: 'npc_dota_hero_winter_wyvern',
    npe_desc_loc: '',
    description: '',
    bio: '',
    abilites: [],
  },
  {
    id: 113,
    name: 'npc_dota_hero_arc_warden',
    npe_desc_loc: '',
    description: '',
    bio: '',
    abilites: [],
  },
  {
    id: 114,
    name: 'npc_dota_hero_monkey_king',
    npe_desc_loc: '',
    description: '',
    bio: '',
    abilites: [],
  },
  {
    id: 119,
    name: 'npc_dota_hero_dark_willow',
    npe_desc_loc: '',
    description: '',
    bio: '',
    abilites: [],
  },
  {
    id: 120,
    name: 'npc_dota_hero_pangolier',
    npe_desc_loc: '',
    description: '',
    bio: '',
    abilites: [],
  },
  {
    id: 121,
    name: 'npc_dota_hero_grimstroke',
    npe_desc_loc: '',
    description: '',
    bio: '',
    abilites: [],
  },
  {
    id: 123,
    name: 'npc_dota_hero_hoodwink',
    npe_desc_loc: '',
    description: '',
    bio: '',
    abilites: [],
  },
  {
    id: 126,
    name: 'npc_dota_hero_void_spirit',
    npe_desc_loc: '',
    description: '',
    bio: '',
    abilites: [],
  },
  {
    id: 128,
    name: 'npc_dota_hero_snapfire',
    npe_desc_loc: '',
    description: '',
    bio: '',
    abilites: [],
  },
  {
    id: 129,
    name: 'npc_dota_hero_mars',
    npe_desc_loc: '',
    description: '',
    bio: '',
    abilites: [],
  },
  {
    id: 135,
    name: 'npc_dota_hero_dawnbreaker',
    npe_desc_loc: '',
    description: '',
    bio: '',
    abilites: [],
  },
  {
    id: 136,
    name: 'npc_dota_hero_marci',
    npe_desc_loc: '',
    description: '',
    bio: '',
    abilites: [],
  },
];

const GetSingleHeroData = props => {
  const { heroName } = props;
  return heroData.find(hero => hero.name === heroName);
};

export default GetSingleHeroData;
